/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check the API is up
         * @description Health endpoint. Smoke-tests that the app starts up.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        /** Create an account */
        post: operations["create_account_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an account */
        get: operations["get_account_api_accounts__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename, retype, or (de)activate an account
         * @description Rename, retype, or deactivate.
         *
         *     There is no DELETE: deactivation is ``{"is_active": false}``, because an
         *     account with movements behind it cannot be removed without orphaning ledger
         *     history.
         */
        patch: operations["update_account_api_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/asset-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the seeded asset classes */
        get: operations["list_asset_classes_api_asset_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset-classes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one asset class */
        get: operations["get_asset_class_api_asset_classes__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        /** Create a category */
        post: operations["create_category_api_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category */
        get: operations["get_category_api_categories__category_id__get"];
        put?: never;
        post?: never;
        /**
         * Deactivate a category
         * @description Soft-delete: the row survives and instruments keep pointing at it.
         */
        delete: operations["deactivate_category_api_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Rename, redescribe, or (de)activate a category */
        patch: operations["update_category_api_categories__category_id__patch"];
        trace?: never;
    };
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List instruments
         * @description Typing the query param as the enum gets validation and OpenAPI docs for free.
         */
        get: operations["list_instruments_api_instruments_get"];
        put?: never;
        /** Create an instrument */
        post: operations["create_instrument_api_instruments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an instrument */
        get: operations["get_instrument_api_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an instrument */
        patch: operations["update_instrument_api_instruments__instrument_id__patch"];
        trace?: never;
    };
    "/api/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List movements
         * @description Voided movements are hidden unless ``include_voided=true``.
         */
        get: operations["list_movements_api_movements_get"];
        put?: never;
        /** Append a movement to the ledger */
        post: operations["create_movement_api_movements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movements/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfer between two owned accounts
         * @description A transfer between own accounts: two linked movements, one ``transfer_id``.
         */
        post: operations["create_transfer_api_movements_transfer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movements/{movement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a movement
         * @description A voided movement is still readable by id — it stays in the ledger.
         */
        get: operations["get_movement_api_movements__movement_id__get"];
        put?: never;
        post?: never;
        /**
         * Annul a movement
         * @description Annul a movement. The row survives; ``voided_at`` is stamped.
         *
         *     Voiding either leg of a transfer voids both.
         */
        delete: operations["void_movement_api_movements__movement_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current tradable positions */
        get: operations["list_positions_api_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total net worth in EUR */
        get: operations["get_net_worth_api_net_worth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/net-worth/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth over time, for charts */
        get: operations["get_net_worth_series_api_net_worth_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/allocation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth broken down by one dimension */
        get: operations["get_allocation_api_allocation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCreate */
        AccountCreate: {
            /**
             * Name
             * @description Unique per owner.
             */
            name: string;
            /**
             * Type
             * @description Free-text kind, e.g. 'broker', 'bank'.
             */
            type: string;
            /**
             * Currency
             * @description ISO 4217 code. Fixed for the account's lifetime.
             */
            currency: string;
        };
        /** AccountRead */
        AccountRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Currency */
            currency: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AccountUpdate
         * @description PATCH semantics: only the provided fields change.
         *
         *     The router applies ``model_dump(exclude_unset=True)`` so an omitted field is
         *     left untouched. ``currency`` is intentionally absent (immutable).
         */
        AccountUpdate: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /**
             * Is Active
             * @description Set to false to deactivate. There is no hard delete.
             */
            is_active?: boolean | null;
        };
        /** AllocationBucketRead */
        AllocationBucketRead: {
            /**
             * Key
             * @description Null means 'uncategorized' (category dimension only).
             */
            key: string | null;
            /** Label */
            label: string;
            /**
             * Value Eur
             * @example 1234.56
             */
            value_eur: string;
            /**
             * Weight
             * @description Share of the total, 0-1. Null when the total is zero.
             */
            weight?: string | null;
        };
        /** AllocationRead */
        AllocationRead: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Dimension */
            dimension: string;
            /**
             * Total Eur
             * @example 1234.56
             */
            total_eur: string;
            /** Buckets */
            buckets: components["schemas"]["AllocationBucketRead"][];
        };
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "tradable" | "cash" | "loan";
        /** AssetClassRead */
        AssetClassRead: {
            /**
             * Code
             * @description The valuation dispatch key, e.g. 'tradable'.
             */
            code: string;
            /**
             * Label
             * @description Human-readable display name.
             */
            label: string;
            /**
             * Description
             * @description What this class means and how it's valued.
             */
            description: string | null;
            /**
             * Sort Order
             * @description Preferred display order, ascending.
             */
            sort_order: number;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /**
             * Name
             * @description Unique display name.
             */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** CategoryRead */
        CategoryRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CategoryUpdate
         * @description PATCH semantics: only the provided fields change.
         */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @description Set to false to deactivate. There is no hard delete.
             */
            is_active?: boolean | null;
        };
        /**
         * Dimension
         * @enum {string}
         */
        Dimension: "asset_class" | "category" | "currency" | "account";
        /**
         * ErrorDetail
         * @description Shape of every 4xx response. Matches what ``main.py``'s domain-error
         *     handlers return for ``NotFoundError`` (404), ``ConflictError`` (409), and
         *     ``DomainRuleError`` (422).
         */
        ErrorDetail: {
            /**
             * Detail
             * @description Human-readable explanation of what went wrong.
             */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstrumentCreate */
        InstrumentCreate: {
            /** Name */
            name: string;
            /**
             * Symbol
             * @description Ticker.
             */
            symbol?: string | null;
            /** @description The valuation dispatch key. Fixed for the instrument's lifetime. */
            asset_class: components["schemas"]["AssetClass"];
            /**
             * Currency
             * @description ISO 4217 code. Fixed for the instrument's life.
             */
            currency: string;
            /**
             * Category Id
             * @description Optional grouping (ETF, crypto, ...). Never affects valuation.
             */
            category_id?: number | null;
            /**
             * Maturity Date
             * @description Loan only.
             */
            maturity_date?: string | null;
            /**
             * Expected Interest
             * @description Loan only.
             */
            expected_interest?: string | null;
            /** @description Loan only. Defaults to 'active' when omitted. */
            status?: components["schemas"]["LoanStatus"] | null;
            /** @description Market-data provider for the price batch script. Tradable only. */
            price_source?: components["schemas"]["PriceSource"] | null;
            /**
             * Provider Ref
             * @description Provider-specific id (yfinance ticker, CoinGecko coin id). Tradable only.
             */
            provider_ref?: string | null;
        };
        /** InstrumentRead */
        InstrumentRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string | null;
            asset_class: components["schemas"]["AssetClass"];
            /** Currency */
            currency: string;
            /** Category Id */
            category_id: number | null;
            /** Maturity Date */
            maturity_date: string | null;
            /** Expected Interest */
            expected_interest: string | null;
            status: components["schemas"]["LoanStatus"] | null;
            price_source: components["schemas"]["PriceSource"] | null;
            /** Provider Ref */
            provider_ref: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * InstrumentUpdate
         * @description PATCH semantics. ``asset_class`` and ``currency`` are immutable.
         *
         *     Loan and pricing fields cannot be cross-checked against the stored
         *     ``asset_class`` here (the schema doesn't see the DB row); the service
         *     enforces that against the stored row plus these changes.
         */
        InstrumentUpdate: {
            /** Name */
            name?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /**
             * Category Id
             * @description Pass null to uncategorise. Must reference an active category.
             */
            category_id?: number | null;
            /** Maturity Date */
            maturity_date?: string | null;
            /** Expected Interest */
            expected_interest?: string | null;
            status?: components["schemas"]["LoanStatus"] | null;
            price_source?: components["schemas"]["PriceSource"] | null;
            /** Provider Ref */
            provider_ref?: string | null;
        };
        /**
         * Interval
         * @enum {string}
         */
        Interval: "day" | "week" | "month";
        /**
         * LoanStatus
         * @enum {string}
         */
        LoanStatus: "active" | "repaid" | "defaulted";
        /** MovementCreate */
        MovementCreate: {
            /**
             * Occurred At
             * Format: date-time
             * @description When it happened. Timezone-aware, required.
             */
            occurred_at: string;
            /**
             * Account Id
             * @description Must be one of the current owner's accounts.
             */
            account_id: number;
            /**
             * Instrument Id
             * @description Required/forbidden/optional depending on type — see below.
             */
            instrument_id?: number | null;
            /** @description Determines which other fields are allowed. */
            type: components["schemas"]["MovementType"];
            /**
             * Quantity
             * @description Always a positive magnitude; direction is implied by type.
             * @example 1234.56
             */
            quantity: string;
            /**
             * Price
             * @description Unit price. Required for buy/sell.
             */
            price?: string | null;
            /**
             * Fee
             * @description Optional transaction cost.
             */
            fee?: string | null;
            /**
             * Currency
             * @description This movement's native currency — not necessarily the account's.
             */
            currency: string;
        };
        /** MovementRead */
        MovementRead: {
            /** Id */
            id: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Account Id */
            account_id: number;
            /** Instrument Id */
            instrument_id: number | null;
            type: components["schemas"]["MovementType"];
            /**
             * Quantity
             * @example 1234.56
             */
            quantity: string;
            /** Price */
            price: string | null;
            /** Fee */
            fee: string | null;
            /** Currency */
            currency: string;
            /**
             * Transfer Id
             * @description Set only for transfer legs; links the two rows.
             */
            transfer_id: string | null;
            /**
             * Source
             * @description Where this row came from, e.g. 'manual'.
             */
            source: string;
            /**
             * External Id
             * @description External id for imported movements (phase 1.5+).
             */
            external_id: string | null;
            /**
             * Voided At
             * @description Set once annulled. Null means still active.
             */
            voided_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MovementType
         * @enum {string}
         */
        MovementType: "purchase" | "sale" | "dividend" | "interest" | "fee" | "deposit" | "withdrawal" | "transfer_out" | "transfer_in" | "principal_repayment";
        /** NetWorthItemRead */
        NetWorthItemRead: {
            /** Asset Class */
            asset_class: string;
            /** Instrument Id */
            instrument_id: number | null;
            /** Account Id */
            account_id: number | null;
            /**
             * Native Value
             * @example 1234.56
             */
            native_value: string;
            /** Native Currency */
            native_currency: string;
            /**
             * Value Eur
             * @example 1234.56
             */
            value_eur: string;
            /** Quantity */
            quantity?: string | null;
            /** Cost Basis */
            cost_basis?: string | null;
            /** Unrealized Pnl */
            unrealized_pnl?: string | null;
        };
        /** NetWorthPointRead */
        NetWorthPointRead: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Total Eur
             * @example 1234.56
             */
            total_eur: string;
        };
        /** NetWorthRead */
        NetWorthRead: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Total Eur
             * @example 1234.56
             */
            total_eur: string;
            /** Items */
            items: components["schemas"]["NetWorthItemRead"][];
        };
        /** NetWorthSeriesRead */
        NetWorthSeriesRead: {
            /** Interval */
            interval: string;
            /** Points */
            points: components["schemas"]["NetWorthPointRead"][];
        };
        /** PositionRead */
        PositionRead: {
            /** Instrument Id */
            instrument_id: number;
            /** Instrument Name */
            instrument_name: string;
            /**
             * Quantity
             * @example 1234.56
             */
            quantity: string;
            /**
             * Cost Basis
             * @example 1234.56
             */
            cost_basis: string;
            /**
             * Realized Pnl
             * @example 1234.56
             */
            realized_pnl: string;
            /** Currency */
            currency: string;
            /**
             * Market Value
             * @description Null for a closed (zero-quantity) position.
             */
            market_value?: string | null;
            /**
             * Unrealized Pnl
             * @description Null when closed.
             */
            unrealized_pnl?: string | null;
            /**
             * Value Eur
             * @description Null when closed.
             */
            value_eur?: string | null;
        };
        /**
         * PriceSource
         * @description Which market-data provider the price batch script (task 1f) fetches from.
         *
         *     NULL on an instrument means the batch skips it (not priced automatically).
         * @enum {string}
         */
        PriceSource: "yfinance" | "coingecko";
        /**
         * TransferCreate
         * @description A transfer between two own accounts.
         *
         *     Expands into two linked movements in the service layer. A wire fee is recorded
         *     separately as a ``fee`` movement, keeping a transfer exactly two symmetric
         *     rows — hence no ``fee`` field here.
         */
        TransferCreate: {
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * From Account Id
             * @description Origin account. Must be one of the owner's.
             */
            from_account_id: number;
            /**
             * To Account Id
             * @description Destination account. Must differ from the origin.
             */
            to_account_id: number;
            /**
             * Instrument Id
             * @description Set only when transferring an instrument rather than cash.
             */
            instrument_id?: number | null;
            /**
             * Quantity
             * @example 1234.56
             */
            quantity: string;
            /** Currency */
            currency: string;
        };
        /**
         * TransferRead
         * @description The two legs of a transfer, assembled by the service layer.
         */
        TransferRead: {
            /**
             * Transfer Id
             * Format: uuid
             */
            transfer_id: string;
            out_movement: components["schemas"]["MovementRead"];
            in_movement: components["schemas"]["MovementRead"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_accounts_api_accounts_get: {
        parameters: {
            query?: {
                /** @description Include deactivated accounts. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description An account with this name already exists for this owner. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_api_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description No account with this id, or it belongs to another owner. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description No account with this id, or it belongs to another owner. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description The new name collides with another of this owner's accounts. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_asset_classes_api_asset_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The asset classes, ordered for display. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetClassRead"][];
                };
            };
        };
    };
    get_asset_class_api_asset_classes__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetClassRead"];
                };
            };
            /** @description No asset class with this code. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: {
                /** @description Include deactivated categories. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description A category with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_api_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description No category with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_category_api_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No category with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description The category is already inactive. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description No category with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description The new name collides with another category. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instruments_api_instruments_get: {
        parameters: {
            query?: {
                /** @description Filter by valuation dispatch key. */
                asset_class?: components["schemas"]["AssetClass"] | null;
                /** @description Filter by grouping category. */
                category_id?: number | null;
                /** @description Include deactivated instruments. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_instrument_api_instruments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"];
                };
            };
            /** @description category_id was given but no such category exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Loan-only or pricing fields were set on a mismatched asset_class, the category is inactive, or price_source/provider_ref weren't set together. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_instrument_api_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"];
                };
            };
            /** @description No instrument with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_instrument_api_instruments__instrument_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"];
                };
            };
            /** @description No instrument with this id, or category_id refers to a nonexistent category. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Loan-only or pricing fields were set on a mismatched asset_class, the new category is inactive, or price_source/provider_ref weren't set together. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    list_movements_api_movements_get: {
        parameters: {
            query?: {
                /** @description Filter to one account. */
                account_id?: number | null;
                /** @description Filter to one instrument. */
                instrument_id?: number | null;
                /** @description Filter to one movement type. */
                type?: components["schemas"]["MovementType"] | null;
                /** @description Only movements at or after this time. */
                occurred_from?: string | null;
                /** @description Only movements at or before this time. */
                occurred_to?: string | null;
                /** @description Include annulled movements (voided_at is set). */
                include_voided?: boolean;
                /** @description Max rows to return. */
                limit?: number;
                /** @description Rows to skip, for pagination. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_movement_api_movements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementRead"];
                };
            };
            /** @description The account (or instrument, if given) does not exist, or the account isn't yours. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description The account is inactive, or the fields don't match the movement type's rules. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    create_transfer_api_movements_transfer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferRead"];
                };
            };
            /** @description One of the accounts does not exist, or isn't yours. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description from_account_id and to_account_id are the same, or an account is inactive. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_movement_api_movements__movement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementRead"];
                };
            };
            /** @description No movement with this id, or its account isn't yours. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    void_movement_api_movements__movement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No movement with this id, or its account isn't yours. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description The movement is already voided. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_positions_get: {
        parameters: {
            query?: {
                /** @description Value as of this date. Defaults to today. */
                date?: string | null;
                /** @description Include closed (zero-quantity) positions. */
                include_closed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionRead"][];
                };
            };
            /** @description A held instrument has no price on or before the requested date. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_net_worth_api_net_worth_get: {
        parameters: {
            query?: {
                /** @description Value as of this date. Defaults to today. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthRead"];
                };
            };
            /** @description A held asset has no price, or a currency has no exchange rate, for the requested date. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_net_worth_series_api_net_worth_series_get: {
        parameters: {
            query?: {
                /** @description First point. Defaults to the first ever movement. */
                from?: string | null;
                /** @description Last point. Defaults to today. */
                to?: string | null;
                /** @description Step between points. */
                interval?: components["schemas"]["Interval"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthSeriesRead"];
                };
            };
            /** @description A held asset has no price or exchange rate for some point in range, from is after to, or the range would produce too many points. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    get_allocation_api_allocation_get: {
        parameters: {
            query?: {
                /** @description How to group net worth. */
                by?: components["schemas"]["Dimension"];
                /** @description Value as of this date. Defaults to today. */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationRead"];
                };
            };
            /** @description A held asset has no price, or a currency has no exchange rate, on this date. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
}
