"""add account.owner_id

Revision ID: f6a988738adc
Revises: 94e8c9705418
Create Date: 2026-07-08 19:09:51.167271

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6a988738adc"
down_revision: str | Sequence[str] | None = "94e8c9705418"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account", sa.Column("owner_id", sa.Integer(), server_default="1", nullable=False)
    )
    op.drop_constraint(op.f("account_name_key"), "account", type_="unique")
    op.create_index(op.f("ix_account_owner_id"), "account", ["owner_id"], unique=False)
    op.create_unique_constraint("uq_account_owner_name", "account", ["owner_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_account_owner_name", "account", type_="unique")
    op.drop_index(op.f("ix_account_owner_id"), table_name="account")
    op.create_unique_constraint(
        op.f("account_name_key"), "account", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("account", "owner_id")
    # ### end Alembic commands ###
